#!/bin/bash
echo $CONFIG_FILE
echo $PWD
cat <<EOT >> $CONFIG_FILE
REACT_APP_BASE_URL=$REACT_APP_BASE_URL
REACT_APP_API_VERSION=$REACT_APP_API_VERSION
#REACT_APP_GOOGLE_PLACES_KEY=$REACT_APP_GOOGLE_PLACES_KEY
#REACT_APP_APIKEY=$REACT_APP_APIKEY
#REACT_APP_AUTHDOMAIN=$REACT_APP_AUTHDOMAIN
#REACT_APP_DATABASEURL=$REACT_APP_DATABASEURL
#REACT_APP_PROJECTID=$REACT_APP_PROJECTID
#REACT_APP_STORAGEBUCKET=$REACT_APP_STORAGEBUCKET
#REACT_APP_MESSAGINGSENDERID=$REACT_APP_MESSAGINGSENDERID
#REACT_APP_APPID=$REACT_APP_APPID
#REACT_APP_MEASUREMENTID=$REACT_APP_MEASUREMENTID
#REACT_APP_SOCKET_URL=$REACT_APP_SOCKET_URL
#REACT_APP_STRIPE_PK=$REACT_APP_STRIPE_PK
EOT
